const createAttractionSchema = {
  type: "object",
  required: [
    "name",
    "description",
    "category",
    "address",
    "city",
    "country",
    "basePrice",
    "openingHours",
  ],
  properties: {
    operatorId: { type: "string", format: "uuid", nullable: true },
    slug: { type: "string", minLength: 2, maxLength: 150, nullable: true },
    name: { type: "string", minLength: 2, maxLength: 200 },
    description: { type: "string", minLength: 10 },
    category: { type: "string" }, // Maps to your AttractionCategory Enum
    address: { type: "string" },
    city: { type: "string" },
    country: { type: "string" },
    latitude: { type: "number", minimum: -90, maximum: 90, nullable: true },
    longitude: { type: "number", minimum: -180, maximum: 180, nullable: true },
    isBookable: { type: "boolean" },
    maxCapacityPerSlot: { type: "integer", minimum: 1 },
    minAdvanceHours: { type: "integer", minimum: 0 },
    maxAdvanceDays: { type: "integer", minimum: 1 },
    averageDurationMinutes: { type: "integer", minimum: 1 },
    basePrice: { type: "number", minimum: 0 },
    dynamicPricing: { type: "boolean" },
    cancellationWindowHours: { type: "integer", minimum: 0 },
    refundPercentage: { type: "integer", minimum: 0, maximum: 100 },
    contactPhone: { type: "string", nullable: true },
    contactEmail: { type: "string", format: "email", nullable: true },
    website: { type: "string", format: "uri", nullable: true },
    images: {
      type: "array",
      items: { type: "string", format: "uri" },
    },
    openingHours: { type: "string" },
    additionalInformation: { type: "string", nullable: true },
    included: { type: "array", items: { type: "string" } },
    notIncluded: { type: "array", items: { type: "string" } },
    whatToBring: { type: "array", items: { type: "string" } },
    relatedAttractionIds: { type: "string", nullable: true },
    travelersPhotos: { type: "object", nullable: true },
    metadata: { type: "object", nullable: true },
  },
  additionalProperties: false,
};

const updateAttractionSchema = {
  type: "object",
  minProperties: 1,
  properties: {
    operatorId: { type: "string", format: "uuid", nullable: true },
    slug: { type: "string", minLength: 2, maxLength: 150, nullable: true },
    name: { type: "string", minLength: 2, maxLength: 200 },
    description: { type: "string", minLength: 10 },
    category: { type: "string" },
    address: { type: "string" },
    city: { type: "string" },
    country: { type: "string" },
    latitude: { type: "number", minimum: -90, maximum: 90, nullable: true },
    longitude: { type: "number", minimum: -180, maximum: 180, nullable: true },
    isBookable: { type: "boolean" },
    maxCapacityPerSlot: { type: "integer", minimum: 1 },
    minAdvanceHours: { type: "integer", minimum: 0 },
    maxAdvanceDays: { type: "integer", minimum: 1 },
    averageDurationMinutes: { type: "integer", minimum: 1 },
    basePrice: { type: "number", minimum: 0 },
    dynamicPricing: { type: "boolean" },
    cancellationWindowHours: { type: "integer", minimum: 0 },
    refundPercentage: { type: "integer", minimum: 0, maximum: 100 },
    contactPhone: { type: "string", nullable: true },
    contactEmail: { type: "string", format: "email", nullable: true },
    website: { type: "string", format: "uri", nullable: true },
    images: {
      type: "array",
      items: { type: "string", format: "uri" },
    },
    openingHours: { type: "string" },
    additionalInformation: { type: "string", nullable: true },
    included: { type: "array", items: { type: "string" } },
    notIncluded: { type: "array", items: { type: "string" } },
    whatToBring: { type: "array", items: { type: "string" } },
    isActive: { type: "boolean" },
  },
  additionalProperties: false,
};

const createTimeSlotSchema = {
  type: "object",
  required: ["attractionId", "date", "startTime", "endTime"],
  properties: {
    attractionId: { type: "string", format: "uuid" },
    date: { type: "string", format: "date-time" }, // Maps to Prisma @db.Date
    startTime: {
      type: "string",
      pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$",
      description: "HH:MM format",
    },
    endTime: {
      type: "string",
      pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$",
      description: "HH:MM format",
    },
    maxSpots: { type: "integer", minimum: 1 },
    priceMultiplier: { type: "number", minimum: 0.1, maximum: 9.9 },
    specialPrice: { type: "number", minimum: 0, nullable: true },
    isBlocked: { type: "boolean" },
    isHoliday: { type: "boolean" },
  },
  additionalProperties: false,
};

const updateTimeSlotSchema = {
  type: "object",
  minProperties: 1,
  properties: {
    availableSpots: { type: "integer", minimum: 0 },
    maxSpots: { type: "integer", minimum: 1 },
    reservedSpots: { type: "integer", minimum: 0 },
    confirmedSpots: { type: "integer", minimum: 0 },
    priceMultiplier: { type: "number", minimum: 0.1, maximum: 9.9 },
    specialPrice: { type: "number", minimum: 0, nullable: true },
    isBlocked: { type: "boolean" },
    isHoliday: { type: "boolean" },
  },
  additionalProperties: false,
};

module.exports = {
  createAttractionSchema,
  createTimeSlotSchema,
  updateTimeSlotSchema,
  updateAttractionSchema,
};
